### ISSUE TITLE
Need CI solution

### ISSUE THREAD

**Issue by DonnieWest** [Wellspring-Fellowship/WSF-Hymnal#4]
We need a way to build our site and automatically deploy. Currently working on a solution via wercker

**Comment by trepidity** [comment]
Did this get completed?

**Comment by DonnieWest** [comment]
No, can't get my docker box to pick up either my ssh key or use a token to
deploy with. I /think/ I know the issue but I might pick your brain later

**Comment by DonnieWest** [comment]
https://github.com/octopress/docker

This looks quite promising for this purpose. Going to be checking this out over the course of the next few days

**Comment by trepidity** [comment]
Docker is really nice. I've been dong stuff with it for owrk.

**Comment by DonnieWest** [comment]
Wercker is now completely docker integrated - pity back in May when I first tried this, I couldn't get some minor quirks worked out in regards to deployment to the final site. This seems to be a good first party alternative to all that extra work :P

But yes, Docker is pretty fantastic
